-- Migration 022: Content fingerprint for cross-field article deduplication
--
-- Adds a content_fingerprint column to articles.
-- This fingerprint is derived from hash(normalized_title | leading_description)
-- and is used to catch near-duplicate articles that share the same body text
-- but have slightly different titles — a common pattern when stories are
-- republished across multiple outlets with minor headline edits.
--
-- Nullable for backward compatibility with existing rows ingested before this
-- migration. New rows generated by gnewsFetcher and the harvester pipeline
-- will always populate this column.
--
-- The index mirrors idx_articles_title_fingerprint: a selective B-tree for
-- point-lookup dedup queries in articleStore.findNearDuplicate().

ALTER TABLE articles
  ADD COLUMN IF NOT EXISTS content_fingerprint TEXT;

CREATE INDEX IF NOT EXISTS idx_articles_content_fingerprint
  ON articles (content_fingerprint);
