/**
 * Company Blog Sources
 *
 * Official blogs from AI model labs, major tech companies,
 * and AI infrastructure/tooling providers.
 *
 * Reliability guide:
 *   10 — Primary AI model lab (direct source for model releases, research)
 *    8 — Official cloud/hardware/MLOps company blog
 */

import type { SourceDefinition } from '@/types/sources';

export const companyBlogSources: SourceDefinition[] = [

  // ── AI model labs (12) ───────────────────────────────────────────────────

  {
    id: 'openai_blog',
    name: 'OpenAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://openai.com/blog/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'anthropic_news',
    name: 'Anthropic Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.anthropic.com/rss.xml',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'deepmind_blog',
    name: 'Google DeepMind Blog',
    type: 'rss',
    category: 'company',
    url: 'https://deepmind.google/blog/rss.xml',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'meta_ai_blog',
    name: 'Meta AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://ai.meta.com/blog/rss/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'nvidia_developer_blog',
    name: 'NVIDIA Developer Blog',
    type: 'rss',
    category: 'company',
    url: 'https://developer.nvidia.com/blog/feed/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'microsoft_ai_blog',
    name: 'Microsoft AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blogs.microsoft.com/ai/feed/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'google_ai_blog',
    name: 'Google AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.google/technology/ai/rss/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'mistral_ai_blog',
    name: 'Mistral AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://mistral.ai/news/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'cohere_blog',
    name: 'Cohere Blog',
    type: 'rss',
    category: 'company',
    url: 'https://cohere.com/blog/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'stability_ai_blog',
    name: 'Stability AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://stability.ai/news/rss',
    reliability: 5,
    enabled: false, // Stability AI entered administration in 2024; blog near-inactive
  },
  {
    id: 'xai_blog',
    name: 'xAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://x.ai/blog/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'perplexity_blog',
    name: 'Perplexity AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.perplexity.ai/rss',
    reliability: 10,
    enabled: true,
  },

  // ── Infrastructure & MLOps company blogs (5) ──────────────────────────────

  {
    id: 'aws_ml_blog',
    name: 'AWS Machine Learning Blog',
    type: 'rss',
    category: 'company',
    url: 'https://aws.amazon.com/blogs/machine-learning/feed/',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'ibm_research_blog',
    name: 'IBM Research Blog',
    type: 'rss',
    category: 'company',
    url: 'https://research.ibm.com/blog/rss',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'weights_biases_blog',
    name: 'Weights & Biases Blog',
    type: 'rss',
    category: 'company',
    url: 'https://wandb.ai/fully-connected/rss.xml',
    reliability: 7,
    enabled: true,
  },
  {
    id: 'lightning_ai_blog',
    name: 'Lightning AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://lightning.ai/blog/feed/',
    reliability: 7,
    enabled: true,
  },
  {
    id: 'semiconductor_engineering',
    name: 'Semiconductor Engineering AI',
    type: 'rss',
    category: 'company',
    url: 'https://semiengineering.com/category/artificial-intelligence/feed/',
    reliability: 7,
    enabled: true,
  },

  // ── AI labs — additional (2) ───────────────────────────────────────────────

  {
    id: 'adept_ai_blog',
    name: 'Adept AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.adept.ai/blog/rss.xml',
    entity: 'Adept AI',
    reliability: 4,
    enabled: false, // Adept AI acquired by Amazon in 2024; blog inactive/dead
  },
  {
    id: 'inflection_ai_blog',
    name: 'Inflection AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://inflection.ai/rss',
    entity: 'Inflection AI',
    reliability: 10,
    enabled: false, // Inflection AI was absorbed by Microsoft in 2024
  },

  // ── AI infrastructure vendors (9) ─────────────────────────────────────────

  {
    id: 'nvidia_ai_blog',
    name: 'NVIDIA AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blogs.nvidia.com/blog/category/ai/feed/',
    entity: 'NVIDIA',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'huggingface_blog',
    name: 'Hugging Face Blog',
    type: 'rss',
    category: 'company',
    url: 'https://huggingface.co/blog/feed.xml',
    entity: 'Hugging Face',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'langchain_blog',
    name: 'LangChain Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.langchain.dev/rss/',
    entity: 'LangChain',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'llamaindex_blog',
    name: 'LlamaIndex Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.llamaindex.ai/blog/rss.xml',
    entity: 'LlamaIndex',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'replicate_blog',
    name: 'Replicate Blog',
    type: 'rss',
    category: 'company',
    url: 'https://replicate.com/blog/rss.xml',
    entity: 'Replicate',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'together_ai_blog',
    name: 'Together AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.together.ai/blog/rss.xml',
    entity: 'Together AI',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'modal_labs_blog',
    name: 'Modal Labs Blog',
    type: 'rss',
    category: 'company',
    url: 'https://modal.com/blog/rss.xml',
    entity: 'Modal Labs',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'octoml_blog',
    name: 'OctoML Blog',
    type: 'rss',
    category: 'company',
    url: 'https://octoml.ai/blog/rss.xml',
    entity: 'OctoML',
    reliability: 4,
    enabled: false, // OctoML acquired by NVIDIA in August 2023; blog shut down
  },
  {
    id: 'cerebras_blog',
    name: 'Cerebras Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.cerebras.net/blog/feed/',
    entity: 'Cerebras',
    reliability: 9,
    enabled: true,
  },

  // ── Robotics & autonomous AI (5) ──────────────────────────────────────────

  {
    id: 'tesla_ai_blog',
    name: 'Tesla AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.tesla.com/blog/rss',
    entity: 'Tesla',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'waymo_blog',
    name: 'Waymo Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.waymo.com/feeds/posts/default',
    entity: 'Waymo',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'cruise_blog',
    name: 'Cruise Blog',
    type: 'rss',
    category: 'company',
    url: 'https://getcruise.com/news/rss',
    entity: 'Cruise',
    reliability: 8,
    enabled: false, // Cruise shut down autonomous operations in 2024
  },
  {
    id: 'boston_dynamics_blog',
    name: 'Boston Dynamics Blog',
    type: 'rss',
    category: 'company',
    url: 'https://bostondynamics.com/blog/rss.xml',
    entity: 'Boston Dynamics',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'figure_ai_blog',
    name: 'Figure AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.figure.ai/blog/rss.xml',
    entity: 'Figure AI',
    reliability: 8,
    enabled: true,
  },

  // ── AI startups & model ecosystem (4) ─────────────────────────────────────

  {
    id: 'character_ai_blog',
    name: 'Character AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.character.ai/rss.xml',
    entity: 'Character AI',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'runwayml_blog',
    name: 'Runway ML Blog',
    type: 'rss',
    category: 'company',
    url: 'https://runwayml.com/blog/rss.xml',
    entity: 'Runway ML',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'pinecone_blog',
    name: 'Pinecone Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.pinecone.io/blog/rss/',
    entity: 'Pinecone',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'assemblyai_blog',
    name: 'AssemblyAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.assemblyai.com/blog/rss.xml',
    entity: 'AssemblyAI',
    reliability: 8,
    enabled: true,
  },

  // ── AI infrastructure & data platforms (4) — Tier 1 ──────────────────────

  {
    id: 'databricks_blog',
    name: 'Databricks Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.databricks.com/blog/feed',
    entity: 'Databricks',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'anyscale_blog',
    name: 'Anyscale Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.anyscale.com/blog/rss',
    entity: 'Anyscale',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'snowflake_ai_blog',
    name: 'Snowflake AI/ML Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.snowflake.com/blog/category/ai-ml/feed/',
    entity: 'Snowflake',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'h2o_ai_blog',
    name: 'H2O.ai Blog',
    type: 'rss',
    category: 'company',
    url: 'https://h2o.ai/blog/rss/',
    entity: 'H2O.ai',
    reliability: 8,
    enabled: true,
  },

  // ── AI model serving & inference (2) — Tier 1 ────────────────────────────

  {
    id: 'groq_blog',
    name: 'Groq Blog',
    type: 'rss',
    category: 'company',
    url: 'https://groq.com/blog/feed/',
    entity: 'Groq',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'sambanova_blog',
    name: 'SambaNova Systems Blog',
    type: 'rss',
    category: 'company',
    url: 'https://sambanova.ai/blog/feed/',
    entity: 'SambaNova',
    reliability: 8,
    enabled: true,
  },

  // ── Applied AI & scale (2) — Tier 1 ──────────────────────────────────────

  {
    id: 'scale_ai_blog',
    name: 'Scale AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://scale.com/blog/feed',
    entity: 'Scale AI',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'amazon_science_blog',
    name: 'Amazon Science Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.amazon.science/blog/rss',
    entity: 'Amazon',
    reliability: 9,
    enabled: true,
  },

  // ── Open-source AI research orgs (2) — Tier 1 ────────────────────────────

  {
    id: 'allenai_blog',
    name: 'Allen Institute for AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://allenai.org/blog/feed.xml',
    entity: 'Allen Institute for AI',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'eleutherai_blog',
    name: 'EleutherAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.eleuther.ai/rss.xml',
    entity: 'EleutherAI',
    reliability: 9,
    enabled: true,
  },

  // ── Enterprise software AI (2) — Tier 2 ──────────────────────────────────

  {
    id: 'adobe_ai_blog',
    name: 'Adobe AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.adobe.com/en/topics/ai-ml-data/rss',
    entity: 'Adobe',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'oracle_ai_blog',
    name: 'Oracle AI & Data Science Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blogs.oracle.com/ai-and-datascience/rss',
    entity: 'Oracle',
    reliability: 7,
    enabled: true,
  },

  // ── AI model labs — wave 2 (6) ────────────────────────────────────────────
  // Added 2026-03: Source expansion week

  {
    id: 'ai21_blog',
    name: 'AI21 Labs Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.ai21.com/blog/rss.xml',
    entity: 'AI21 Labs',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'writer_ai_blog',
    name: 'Writer AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://writer.com/blog/feed/',
    entity: 'Writer',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'reka_ai_blog',
    name: 'Reka AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.reka.ai/blog/rss.xml',
    entity: 'Reka AI',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'aleph_alpha_blog',
    name: 'Aleph Alpha Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.aleph-alpha.com/blog/rss',
    entity: 'Aleph Alpha',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'zhipu_ai_blog',
    name: 'Zhipu AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.zhipuai.cn/en/news/rss',
    entity: 'Zhipu AI',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'minimax_blog',
    name: 'MiniMax Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.minimaxi.com/blog/feed',
    entity: 'MiniMax',
    reliability: 8,
    enabled: true,
  },

  // ── AI infrastructure — wave 2 (8) ───────────────────────────────────────

  {
    id: 'fireworks_ai_blog',
    name: 'Fireworks AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://fireworks.ai/blog/rss',
    entity: 'Fireworks AI',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'baseten_blog',
    name: 'Baseten Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.baseten.co/blog/rss/',
    entity: 'Baseten',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'coreweave_blog',
    name: 'CoreWeave Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.coreweave.com/blog/rss.xml',
    entity: 'CoreWeave',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'lambda_labs_blog',
    name: 'Lambda Labs Blog',
    type: 'rss',
    category: 'company',
    url: 'https://lambdalabs.com/blog/rss',
    entity: 'Lambda',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'vast_ai_blog',
    name: 'Vast.ai Blog',
    type: 'rss',
    category: 'company',
    url: 'https://vast.ai/blog/rss',
    entity: 'Vast.ai',
    reliability: 7,
    enabled: true,
  },
  {
    id: 'weights_and_biases_research',
    name: 'Weights & Biases Research',
    type: 'rss',
    category: 'company',
    url: 'https://wandb.ai/site/research/rss.xml',
    entity: 'Weights & Biases',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'unsloth_blog',
    name: 'Unsloth Blog',
    type: 'rss',
    category: 'company',
    url: 'https://unsloth.ai/blog/rss',
    entity: 'Unsloth',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'cursor_blog',
    name: 'Cursor AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.cursor.com/blog/rss.xml',
    entity: 'Cursor',
    reliability: 8,
    enabled: true,
  },

  // ── AI coding & developer tools (4) ──────────────────────────────────────

  {
    id: 'vercel_ai_blog',
    name: 'Vercel AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://vercel.com/blog/rss.xml',
    entity: 'Vercel',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'replit_blog',
    name: 'Replit Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.replit.com/feed.xml',
    entity: 'Replit',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'sourcegraph_blog',
    name: 'Sourcegraph Blog',
    type: 'rss',
    category: 'company',
    url: 'https://about.sourcegraph.com/blog/rss.xml',
    entity: 'Sourcegraph',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'tabnine_blog',
    name: 'Tabnine Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.tabnine.com/blog/feed/',
    entity: 'Tabnine',
    reliability: 7,
    enabled: true,
  },

  // ── Applied AI companies (4) ─────────────────────────────────────────────

  {
    id: 'elevenlab_blog',
    name: 'ElevenLabs Blog',
    type: 'rss',
    category: 'company',
    url: 'https://elevenlabs.io/blog/rss/',
    entity: 'ElevenLabs',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'midjourney_blog',
    name: 'Midjourney Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.midjourney.com/blog/rss',
    entity: 'Midjourney',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'pika_labs_blog',
    name: 'Pika Labs Blog',
    type: 'rss',
    category: 'company',
    url: 'https://pika.art/blog/rss',
    entity: 'Pika',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'suno_ai_blog',
    name: 'Suno AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://suno.com/blog/rss',
    entity: 'Suno',
    reliability: 8,
    enabled: true,
  },
];
