/**
 * Company Blog Sources
 *
 * Official blogs from AI model labs, major tech companies,
 * and AI infrastructure/tooling providers.
 *
 * Reliability guide:
 *   10 — Primary AI model lab (direct source for model releases, research)
 *    8 — Official cloud/hardware/MLOps company blog
 */

import type { SourceDefinition } from '@/types/sources';

export const companyBlogSources: SourceDefinition[] = [

  // ── AI model labs (12) ───────────────────────────────────────────────────

  {
    id: 'openai_blog',
    name: 'OpenAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://openai.com/blog/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'anthropic_news',
    name: 'Anthropic Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.anthropic.com/rss.xml',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'deepmind_blog',
    name: 'Google DeepMind Blog',
    type: 'rss',
    category: 'company',
    url: 'https://deepmind.google/blog/rss.xml',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'meta_ai_blog',
    name: 'Meta AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://ai.meta.com/blog/rss/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'nvidia_developer_blog',
    name: 'NVIDIA Developer Blog',
    type: 'rss',
    category: 'company',
    url: 'https://developer.nvidia.com/blog/feed/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'microsoft_ai_blog',
    name: 'Microsoft AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blogs.microsoft.com/ai/feed/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'google_ai_blog',
    name: 'Google AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.google/technology/ai/rss/',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'mistral_ai_blog',
    name: 'Mistral AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://mistral.ai/news/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'cohere_blog',
    name: 'Cohere Blog',
    type: 'rss',
    category: 'company',
    url: 'https://cohere.com/blog/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'stability_ai_blog',
    name: 'Stability AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://stability.ai/news/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'xai_blog',
    name: 'xAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://x.ai/blog/rss',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'perplexity_blog',
    name: 'Perplexity AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.perplexity.ai/rss',
    reliability: 10,
    enabled: true,
  },

  // ── Infrastructure & MLOps company blogs (5) ──────────────────────────────

  {
    id: 'aws_ml_blog',
    name: 'AWS Machine Learning Blog',
    type: 'rss',
    category: 'company',
    url: 'https://aws.amazon.com/blogs/machine-learning/feed/',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'ibm_research_blog',
    name: 'IBM Research Blog',
    type: 'rss',
    category: 'company',
    url: 'https://research.ibm.com/blog/rss',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'weights_biases_blog',
    name: 'Weights & Biases Blog',
    type: 'rss',
    category: 'company',
    url: 'https://wandb.ai/fully-connected/rss.xml',
    reliability: 7,
    enabled: true,
  },
  {
    id: 'lightning_ai_blog',
    name: 'Lightning AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://lightning.ai/blog/feed/',
    reliability: 7,
    enabled: true,
  },
  {
    id: 'semiconductor_engineering',
    name: 'Semiconductor Engineering AI',
    type: 'rss',
    category: 'company',
    url: 'https://semiengineering.com/category/artificial-intelligence/feed/',
    reliability: 7,
    enabled: true,
  },

  // ── AI labs — additional (2) ───────────────────────────────────────────────

  {
    id: 'adept_ai_blog',
    name: 'Adept AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.adept.ai/blog/rss.xml',
    entity: 'Adept AI',
    reliability: 10,
    enabled: true,
  },
  {
    id: 'inflection_ai_blog',
    name: 'Inflection AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://inflection.ai/rss',
    entity: 'Inflection AI',
    reliability: 10,
    enabled: true,
  },

  // ── AI infrastructure vendors (9) ─────────────────────────────────────────

  {
    id: 'nvidia_ai_blog',
    name: 'NVIDIA AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blogs.nvidia.com/blog/category/ai/feed/',
    entity: 'NVIDIA',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'huggingface_blog',
    name: 'Hugging Face Blog',
    type: 'rss',
    category: 'company',
    url: 'https://huggingface.co/blog/feed.xml',
    entity: 'Hugging Face',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'langchain_blog',
    name: 'LangChain Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.langchain.dev/rss/',
    entity: 'LangChain',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'llamaindex_blog',
    name: 'LlamaIndex Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.llamaindex.ai/blog/rss.xml',
    entity: 'LlamaIndex',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'replicate_blog',
    name: 'Replicate Blog',
    type: 'rss',
    category: 'company',
    url: 'https://replicate.com/blog/rss.xml',
    entity: 'Replicate',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'together_ai_blog',
    name: 'Together AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.together.ai/blog/rss.xml',
    entity: 'Together AI',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'modal_labs_blog',
    name: 'Modal Labs Blog',
    type: 'rss',
    category: 'company',
    url: 'https://modal.com/blog/rss.xml',
    entity: 'Modal Labs',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'octoml_blog',
    name: 'OctoML Blog',
    type: 'rss',
    category: 'company',
    url: 'https://octoml.ai/blog/rss.xml',
    entity: 'OctoML',
    reliability: 9,
    enabled: true,
  },
  {
    id: 'cerebras_blog',
    name: 'Cerebras Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.cerebras.net/blog/feed/',
    entity: 'Cerebras',
    reliability: 9,
    enabled: true,
  },

  // ── Robotics & autonomous AI (5) ──────────────────────────────────────────

  {
    id: 'tesla_ai_blog',
    name: 'Tesla AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.tesla.com/blog/rss',
    entity: 'Tesla',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'waymo_blog',
    name: 'Waymo Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.waymo.com/feeds/posts/default',
    entity: 'Waymo',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'cruise_blog',
    name: 'Cruise Blog',
    type: 'rss',
    category: 'company',
    url: 'https://getcruise.com/news/rss',
    entity: 'Cruise',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'boston_dynamics_blog',
    name: 'Boston Dynamics Blog',
    type: 'rss',
    category: 'company',
    url: 'https://bostondynamics.com/blog/rss.xml',
    entity: 'Boston Dynamics',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'figure_ai_blog',
    name: 'Figure AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.figure.ai/blog/rss.xml',
    entity: 'Figure AI',
    reliability: 8,
    enabled: true,
  },

  // ── AI startups & model ecosystem (4) ─────────────────────────────────────

  {
    id: 'character_ai_blog',
    name: 'Character AI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://blog.character.ai/rss.xml',
    entity: 'Character AI',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'runwayml_blog',
    name: 'Runway ML Blog',
    type: 'rss',
    category: 'company',
    url: 'https://runwayml.com/blog/rss.xml',
    entity: 'Runway ML',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'pinecone_blog',
    name: 'Pinecone Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.pinecone.io/blog/rss/',
    entity: 'Pinecone',
    reliability: 8,
    enabled: true,
  },
  {
    id: 'assemblyai_blog',
    name: 'AssemblyAI Blog',
    type: 'rss',
    category: 'company',
    url: 'https://www.assemblyai.com/blog/rss.xml',
    entity: 'AssemblyAI',
    reliability: 8,
    enabled: true,
  },
];
